### ISSUE TITLE
ModuleNotFoundError: No module named 'binance.client'; 'binance' is not a package

### ISSUE THREAD

**Issue by llattanzio** [Kalaborative/binance-bot#1]
Hi there, 
I'm quite new on this and I need some help to fix this Issue.
I tried to run binance_bot.py but i have always tha same error.
My python verison is 3.6.4
I have imported Binance api trough pip install binance
  
C:\binance-bot-master>python binance_bot.py
Traceback (most recent call last):
  File "binance_bot.py", line 5, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance.client'; 'binance' is not a package

**Comment by Kalaborative** [comment]
Hi,

It must've been a typo on my end. The correct package to install should be called **python-binance**. Try doing `pip install python-binance`. 

Let me know if that works 👍

**Comment by Kalaborative** [comment]
Check the readme file for more details, I updated it 😄
